CREATE TABLE tasks (
		id SERIAL PRIMARY KEY,
		title VARCHAR(255) NOT NULL UNIQUE,
		description VARCHAR(1000) NOT NULL,
		is_completed BOOLEAN DEFAULT FALSE,
		created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
		done_at TIMESTAMP DEFAULT NULL
	)